controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    demise_fighter_605.setImage(img`
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff............
        .ffeeeeef22ff...........
        .feeeeffeeeef...........
        .fffffee2222ef..........
        fffe222ffffe2f..........
        ffffffffeeefff..........
        fefe44ebf44eef..........
        .fee4d4bfddef...........
        ..feee4dddee.c..........
        ...f2222eeddeccccccc....
        ...f444e44ddecddddd.....
        ...fffffeeee.ccccc......
        ..ffffffff...c..........
        ..fff..ff...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
let demise_fighter_605: Sprite = null
tiles.setCurrentTilemap(tilemap`level2`)
demise_fighter_605 = sprites.create(img`
    ........................
    ........................
    ........................
    ...........ffff.........
    .........fff22fff.......
    ........fff2222fff......
    .......fffeeeeeefff.....
    .......ffe222222eef.....
    .......fe2ffffff2ef.....
    .......ffffeeeeffff.....
    ......ffefbf44fbfeff....
    ......fee41fddf14eef....
    .....fdfeeddddd4eff.....
    .....fbffee444edd4e.....
    .....fbf4f2222edde......
    .....fcf.f22cccee.......
    ......ff.f44cdc4f.......
    .........fffddcff.......
    ..........fddcff........
    .........cddc...........
    .........cdc............
    .........cc.............
    ........................
    ........................
    `, SpriteKind.Player)
scene.cameraFollowSprite(demise_fighter_605)
controller.moveSprite(demise_fighter_605, 100, 100)
